# image: node:4.2.2

cache:
  paths:
  - node_modules/

部署到生产环境:
  script:
    - npm install --registry=https://registry.npm.taobao.org
    - npm run build
    - rm -rf /opt/iot-front/*
    - cp -R dist/* /opt/iot-front/
  tags:
    - dev
  only:
    - master
  when: manual
